name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
  
    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip install -r requirements.txt

          git fetch --prune --unshallow
          
          # Pull dataset with DVC 
          pip install dvc[all]
          dvc pull data
          
          # Reproduce pipeline if any changes detected in dependencies
          dvc repro

         
          
